### ISSUE TITLE
[Bug] Robot Libraries window for MacOS

### ISSUE THREAD

**Issue by lin-ycv** [visose/Robots#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What Robots version are you using?

1.1.8

### What Rhino version are you using?

Rhino 7 on MacOS

### Current Behavior

Robot Libraries window is not displaying correctly, cannot read names.
![image](https://user-images.githubusercontent.com/60565737/156691890-b050a961-bc16-4a68-bed0-d106b267e782.png)

### Expected Behavior

text and icons to be displayed correctly
![image](https://user-images.githubusercontent.com/60565737/156691789-c91eb61e-f62c-42ca-98e2-f0f4d341c40b.png)

### Steps To Reproduce

open Robot Libraries window in MacOS

**Comment by visose** [comment]
Thanks. I'll check why the cells of the grid are so narrow. I think the rest of the text not showing up (in the button, title, description) is probably because I have forced a white background and the text color in dark theme is also white. I'll remove any forced styling to avoid this.

**Comment by visose** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/5129614/156926354-8c09ba28-ba96-4622-bc8e-3dbb654c2508.png">

I think this is fixed now. Had to force the height of the cells, since in mac it doesn't compute the correct height (there's an issue open in the eto repo about this).
I had to also force the background color of the panel to be transparent, if not, it uses a gray color rather than the dark theme background.
I fixed also the spinners next to the buttons, they where cropped a bit on mac.

I also noticed the toolbar icons look terrible in mac, and not only the Robots ones. Do people use Rhino/Grasshopper with the dark theme?

**Comment by visose** [comment]
@lin-ycv could you check if it looks fixed in the latest release, and if so you can close the issue.

**Comment by visose** [comment]
I just noticed another issue with the form in Mac, the icon on the list doesn't change when installing/updating/deleting a library. This also seems like an Eto issue in Mac.

I fixed it by updating the list using a different mechanism, it will go into the next update.

**Comment by lin-ycv** [comment]
Sorry for the delayed reply, I don't have ready access to a Mac., but I've just checked and everything seems to be properly formatted now.
The icon issue I don't think is a big deal, will appear as checked after pressing refresh, maybe force a refresh after download?

Most people I know use the dark theme on mac, but I don't think it's that terrible, especially since we usually just use keyword search instead of the toolbar.

Thanks.
